// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVG_rjXDntQ6tMnVfMWjdD86QwmX-D5OE',
    appId: '1:1002828667471:web:24eeb4899e156d75d8a83a',
    messagingSenderId: '1002828667471',
    projectId: 'kriyetaeventmanage',
    authDomain: 'kriyetaeventmanage.firebaseapp.com',
    storageBucket: 'kriyetaeventmanage.appspot.com',
    measurementId: 'G-SKN61WFSFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3Fch2B4KYhv65NmJh7HlNu9cdzdWujc',
    appId: '1:1002828667471:android:1df08e94a9ac364ad8a83a',
    messagingSenderId: '1002828667471',
    projectId: 'kriyetaeventmanage',
    storageBucket: 'kriyetaeventmanage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuVnrt0KcW7Dw5VYtq5p7znhbhP3f2yQ4',
    appId: '1:1002828667471:ios:8096218d784bdf39d8a83a',
    messagingSenderId: '1002828667471',
    projectId: 'kriyetaeventmanage',
    storageBucket: 'kriyetaeventmanage.appspot.com',
    iosBundleId: 'com.example.kriyetaEventManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuVnrt0KcW7Dw5VYtq5p7znhbhP3f2yQ4',
    appId: '1:1002828667471:ios:7d4c28ddfc04d1a2d8a83a',
    messagingSenderId: '1002828667471',
    projectId: 'kriyetaeventmanage',
    storageBucket: 'kriyetaeventmanage.appspot.com',
    iosBundleId: 'com.example.kriyetaEventManage.RunnerTests',
  );
}
